version: '3'

services:
  web:
    image: "node:alpine"
    links:
      - redis
    ports:
      - '80:8080'
    working_dir: /app
    volumes:
      - $PWD:/app
    command: "node server.js --redis=redis://redis:6379"

  redis:
    image: "redis:alpine"
